version: '2'
services:
  database:
    container_name: dhis2-spla-db
    image: mdillon/postgis:9.5
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis
      POSTGRES_PASSWORD: dhis
      POSTGRES_DB_TARGET: dhis-target
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - spla:/var/lib/postgresql/data/pgdata

  web:
    container_name: dhis2-spla-web
    image: researchtriangle/dhis2-web:2.27-tomcat7-jre8-latest
    environment:
      JAVA_OPTS: "-Xmx1024m -Xms4000m -Dtomcat.util.http.parser.HttpParser.requestTargetAllow=|{}" 
      POSTGRES_DB: dhis
    ports:
      - 8085:8080
    depends_on:
      - database
    entrypoint: ./wait-for-it.sh -t 0 database:5432 --
    command: catalina.sh run # https://github.com/docker/compose/issues/3140

volumes:
  spla: