version: '2'
services:
  database:
    container_name: dhis2-guinea
    image: researchtriangle/dhis2-db:2.30-guinea-national
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis
      POSTGRES_PASSWORD: dhis
      POSTGRES_DB_TARGET: dhis-target
      PGDATA: /var/lib/postgresql/data/pgdata
    command: postgres -c max_locks_per_transaction=256
    ports:
      - 5432:5432
    volumes:
      - guinea2:/var/lib/postgresql/data/pgdata

  web:
    container_name: dhis2-guinea-web
    image: researchtriangle/dhis2-web:2.30-tomcat7-jre8-latest
    environment:
      JAVA_OPTS: "-Xmx1024m -Xms4000m"
      POSTGRES_DB: dhis
    ports:
      - 8085:8080
    depends_on:
      - database
    entrypoint: ./wait-for-it.sh -t 0 database:5432 --
    command: catalina.sh run # https://github.com/docker/compose/issues/3140

volumes:
  guinea2: