version: '2'
services:
  database:
    container_name: dhis2-updf
    image: mdillon/postgis:9.5
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis
      POSTGRES_PASSWORD: dhis
      POSTGRES_DB_TARGET: dhis-target
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - updf:/var/lib/postgresql/data/pgdata

  web:
    container_name: dhis2-web
    image: reearchtriangle/dhis2-web:2.28-tomcat7-jre8-latest
    environment:
      JAVA_OPTS: "-Xmx1024m -Xms4000m"
      POSTGRES_DB: dhis
    ports:
      - 8085:8080
    depends_on:
      - database
    entrypoint: ./wait-for-it.sh -t 0 database:5432 --
    command: catalina.sh run # https://github.com/docker/compose/issues/3140

volumes:
  updf: