version: '2'
services:
  database:
    container_name: dhis2-actntd-database
    image: mdillon/postgis:10
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis
      POSTGRES_PASSWORD: dhis
      POSTGRES_DB_TARGET: dhis-target
      PGDATA: actntd:/var/lib/postgresql/data/pgdata:z
    ports:
     - "5432:5432"
  web:
    container_name: dhis2-actntd-web
    image: researchtriangle/dhis2-web:2.31.1-tomcat7-jre8-20190415
    environment:
      JAVA_OPTS: "-Xmx1024m -Xms4000m"
      POSTGRES_DB: dhis
    ports:
      - "8085:8080"
    depends_on:
      - database
    entrypoint: ./wait-for-it.sh -t 0 database:5432 --
    command: catalina.sh run # https://github.com/docker/compose/issues/3140
  
volumes:
  actntd:
